# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
    working_directory: ~/repo
    parallelism: 1
    docker:
      - image: circleci/node:7.10

aliases:
    - &attachWorkspace
        attach_workspace:
          at: ~/repo

    - &restoreCache
        restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}

    - &storeDeploy
        store_artifacts:
          path: ./deploy

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build

      - persist_to_workspace:
          root: ~/repo
          paths:
            - .git
            - .nycrc
            - outputs
            - src
            - test
            - package.json
            - tsconfig.json
            - tslint.json

  lint:
    <<: *defaults

    steps:
      - *attachWorkspace
      - *restoreCache

      - run:
          name: Run LINT
          command: npm run lint

  test:
    <<: *defaults

    steps:
      - *attachWorkspace
      - *restoreCache
      - run:
          name: Unit Tests
          command: npm run test
      - store_test_results:
          path: ./outputs/reports/junit
      - store_artifacts:
          path: ./outputs/reports
      - store_artifacts:
          path: ./dist/src/main
      - persist_to_workspace:
          root: ~/repo
          paths:
            - outputs

  release:
    <<: *defaults

    steps:
      - *attachWorkspace
      - *restoreCache
      - run:
          name: Release Version
          command: npm run version:release

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - release:
          requires:
            - lint
            - test
          filters:
            branches:
              only: master